stages:
  featurize:
    cmd: python src/featurization.py
    deps:
    - data/insurance.csv
    - src/featurization.py
    outs:
      - data/features/insurance_featurized.csv
  scale_split:
    cmd: python src/scale_split.py
    deps:
    - data/features/insurance_featurized.csv
    - src/scale_split.py
    params:
    - scale_split.random_state
    - scale_split.test_size
    outs:
      - data/split/train.csv
      - data/split/test.csv
  train_n_evaluate:
    cmd: python src/train_n_evaluate.py
    deps:
    - data/split/test.csv
    - data/split/train.csv
    - src/train_n_evaluate.py
    params:
    - train.ccp_alpha
    - train.cv
    - train.max_depth
    - train.min_samples_leaf
    - train.min_samples_split
    - train.n_estimators
    - train.random_state
    outs:
      - rand_forest_insurance.pkl
