scale_split:
  test_size: 0.3
  random_state: 42
train:
  cv: 4
  ccp_alpha: [0.0001, 0.001, 0.01, 0.05, 0.5]
  n_estimators: [50, 100, 150, 800]
  random_state: 42
  max_depth: [5, 10, 15]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 4]